#!/usr/bin/env python3
"""
Generate SQL to seed annotator accounts into Supabase app_users.

Reads:  annotators.csv  (username,password — one per row)
Writes: annotators_seed.sql  (INSERT ... ON CONFLICT DO UPDATE)

Usage:
    python scripts/seed_annotators.py

Both the input CSV and output SQL contain plaintext passwords / hashes.
Neither file should be committed to version control (.gitignore covers them).
"""

import csv
import os
import sys

import bcrypt

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(SCRIPT_DIR)

INPUT_FILE = os.path.join(REPO_ROOT, "annotators.csv")
OUTPUT_FILE = os.path.join(REPO_ROOT, "annotators_seed.sql")


def hash_password(plain: str) -> str:
    return bcrypt.hashpw(plain.encode("utf-8"), bcrypt.gensalt()).decode("utf-8")


def main():
    if not os.path.exists(INPUT_FILE):
        print(f"Error: {INPUT_FILE} not found.")
        print(f"Create it with columns: username,password")
        sys.exit(1)

    with open(INPUT_FILE, encoding="utf-8") as f:
        reader = csv.DictReader(f)
        rows = list(reader)

    if not rows:
        print("No rows found in annotators.csv.")
        sys.exit(1)

    lines = [
        "-- Generated by scripts/seed_annotators.py",
        "-- Paste this into the Supabase SQL Editor to create/update annotator accounts.",
        "-- Do NOT commit this file to version control.",
        "",
    ]

    for r in rows:
        username = r["username"].strip()
        password = r["password"].strip()
        if not username or not password:
            continue
        pw_hash = hash_password(password)
        # Escape single quotes in hash (bcrypt hashes don't contain them, but be safe)
        pw_hash_escaped = pw_hash.replace("'", "''")
        lines.append(
            f"INSERT INTO app_users (username, password_hash, is_active) "
            f"VALUES ('{username}', '{pw_hash_escaped}', TRUE) "
            f"ON CONFLICT (username) DO UPDATE SET "
            f"password_hash = EXCLUDED.password_hash, is_active = TRUE;"
        )

    lines.append("")

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"Read {len(rows)} accounts from {INPUT_FILE}")
    print(f"Wrote SQL to {OUTPUT_FILE}")
    print(f"Paste the contents of {OUTPUT_FILE} into the Supabase SQL Editor.")


if __name__ == "__main__":
    main()
